server:
  port: 8081
  servlet:
    context-path: /user

spring:
  main:
    allow-bean-definition-overriding: true
  config:
    activate:
      on-profile: local
  application:
    name: user-server

  jackson:
    time-zone: Asia/Seoul

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/unimal-user
    username: postgres
    password: 5432

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: efb296d5c6356e127cef527215b99d8a
            client-secret: jnAT7TuGXqIqc0TRkyJo7faeM53czsmq
            redirect-uri: http://localhost:8080/user/login/oauth2/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client-authentication-method: client_secret_post
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
